### ISSUE TITLE
Match Notification QoL

### ISSUE THREAD

**Issue by screetox** [static-var/vlr-gg#130]
It would be awesome to be able to toggle match notifications for an entire event so you don't have to open every single match to activate the notification.

**Comment by static-var** [comment]
Hey @screetox thanks for the suggestion, 
We had thought about this earlier and beta tested it with a few friends, unfortunately it ended up becoming too spamy / unnecessary, especially during the early stages (Open quals) of a tournament where there are several matches going on at the same time.

Alternativly we also tried making notification per team basis so one could subscribe to your favorite team, but ran into some challenges because of some important information required for this feature was not always available from vlr website. So, dev who maintains backend for this project is trying some alternate approch to counter this issue. Hopefully we should be able to figure this out.

**Comment by screetox** [comment]
Thank you for all the information. I'm sure there will be a great solution found in the future. Keep up the awesome work!

I'm closing the issue because as you stated this specific case is not planned due to spamy / unnecessary notifications.
